import pytest
from d365fo_tools.builder import Builder, PackageReference, BuildOrder
from d365fo_tools.config import config
from .conftest import PACKAGES_DIR, LOG_DIR

pytestmark = pytest.mark.asyncio


def test_get_package_references_with_packages_filter(log):
    result = PackageReference(['Application.*']).run()

    assert result == {
        'ApplicationCommon': {'ApplicationPlatform', 'ApplicationFoundation'},
        'ApplicationFoundation': {'ApplicationPlatform'},
        'ApplicationFoundationFormAdaptor': {'ApplicationFoundation', 'ApplicationPlatform'},
        'ApplicationPlatform': set(),
        'ApplicationPlatformFormAdaptor': {'ApplicationPlatform'},
        'ApplicationSuiteFormAdaptor': {'ApplicationFoundation', 'ApplicationPlatform'},
        'ApplicationWorkspaces': {'ApplicationCommon',
                                  'ApplicationFoundation',
                                  'ApplicationPlatform'},
        'ApplicationWorkspacesFormAdaptor': {'ApplicationFoundation',
                                             'ApplicationPlatform',
                                             'ApplicationWorkspaces'}
    }


def test_get_package_references_catch_all_filter(log):
    config.set('DEFAULTS', 'package_filter', '.*')
    result = PackageReference().run()

    assert result == {
        'ATLApplicationSuite': {'AppTroubleshooting', 'AppTroubleshootingCore', 'ApplicationCommon',
                                'ApplicationFoundation', 'ApplicationPlatform', 'AtlCoreFinancial', 'AtlCostAccounting',
                                'AtlFoundation', 'AtlPersonnel', 'BankTypes', 'Calendar', 'CaseManagement',
                                'ContactPerson', 'Currency', 'DemoDataWellKnownValues', 'Dimensions', 'Directory',
                                'FiscalBooks', 'GeneralLedger', 'Kitting', 'Ledger', 'Measurement', 'PersonnelCore',
                                'PersonnelManagement', 'Policy', 'Retail', 'RetailEod', 'SourceDocumentation',
                                'SourceDocumentationTypes', 'Subledger', 'Tax', 'TaxEngine', 'TestEssentials',
                                'UnitOfMeasure'},
        'AccountsPayableMobile': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'BankTypes',
                                  'Calendar', 'ContactPerson', 'Currency', 'Dimensions', 'Directory',
                                  'ElectronicReporting', 'ElectronicReportingForAx', 'ElectronicReportingMapping',
                                  'FinancialReporting', 'FiscalBooks', 'GeneralLedger', 'Ledger', 'Measurement',
                                  'Policy', 'SourceDocumentation', 'SourceDocumentationTypes', 'Subledger', 'Tax',
                                  'TestEssentials', 'UnitOfMeasure'},
        'AppTroubleshooting': {'AppTroubleshootingCore', 'ApplicationCommon', 'ApplicationFoundation',
                               'ApplicationPlatform', 'CaseManagement', 'ContactPerson', 'Dimensions', 'Directory',
                               'FiscalBooks', 'GeneralLedger', 'Kitting', 'Ledger', 'Project', 'Retail',
                               'SourceDocumentation', 'SourceDocumentationTypes', 'Subledger', 'Tax', 'TaxEngine',
                               'UnitOfMeasure', 'WarehousePlanning'},
        'AppTroubleshootingCore': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform'},
        'ApplicationCommon': {'ApplicationFoundation', 'ApplicationPlatform'},
        'ApplicationFoundation': {'ApplicationPlatform'},
        'ApplicationFoundationFormAdaptor': {'ApplicationFoundation', 'ApplicationPlatform', 'TestEssentials'},
        'ApplicationPlatform': set(),
        'ApplicationPlatformFormAdaptor': {'TestEssentials', 'ApplicationPlatform'},
        'ApplicationSuiteFormAdaptor': {'ApplicationFoundation', 'ApplicationPlatform', 'BankTypes', 'Calendar',
                                        'CaseManagement', 'ContactPerson', 'Currency', 'Dimensions', 'Directory',
                                        'FiscalBooks', 'GeneralLedger', 'Ledger', 'Measurement', 'PersonnelCore',
                                        'PersonnelManagement', 'Policy', 'Retail', 'SourceDocumentation',
                                        'SourceDocumentationTypes', 'Subledger', 'Tax', 'TestEssentials',
                                        'UnitOfMeasure'},
        'ApplicationWorkspaces': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'BankTypes',
                                  'BusinessProcess', 'Calendar', 'CaseManagement', 'ContactPerson', 'CostAccounting',
                                  'Currency', 'DOM', 'Dimensions', 'Directory', 'ElectronicReporting',
                                  'FinanceInsightsContracts', 'FiscalBooks', 'GeneralLedger', 'Ledger', 'PersonnelCore',
                                  'PersonnelManagement', 'ProcessAutomation', 'Project', 'Retail',
                                  'RetailTeamsIntegration', 'SourceDocumentation', 'SourceDocumentationTypes',
                                  'Subledger', 'Tax', 'UnitOfMeasure'},
        'ApplicationWorkspacesFormAdaptor': {'ApplicationFoundation', 'ApplicationPlatform', 'ApplicationWorkspaces',
                                             'BankTypes', 'Directory', 'TestEssentials'},
        'AssetLeasing': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'BankTypes',
                         'BusinessProcess', 'Calendar', 'CaseManagement', 'ContactPerson', 'Currency', 'DataSharing',
                         'Dimensions', 'Directory', 'ElectronicReporting', 'ElectronicReportingCore',
                         'ElectronicReportingForAx', 'ElectronicReportingMapping', 'FinancialReporting', 'FiscalBooks',
                         'GeneralLedger', 'Ledger', 'Measurement', 'Personnel', 'PersonnelCore', 'PersonnelManagement',
                         'Policy', 'Project', 'Retail', 'SourceDocumentation', 'SourceDocumentationTypes', 'Subledger',
                         'Tax', 'TaxEngine', 'UnitOfMeasure'},
        'AtlCoreFinancial': {'ApplicationFoundation', 'ApplicationPlatform', 'Calendar', 'Currency', 'Dimensions',
                             'Directory', 'Ledger', 'SourceDocumentationTypes'},
        'AtlCostAccounting': {'ApplicationFoundation', 'ApplicationPlatform', 'AtlFoundation', 'Calendar',
                              'CostAccounting', 'Currency', 'Directory', 'Ledger', 'UnitOfMeasure'},
        'AtlFoundation': {'ApplicationFoundation', 'ApplicationPlatform'},
        'AtlMaterialhandling': {'ApplicationFoundation', 'ApplicationPlatform', 'AtlFoundation',
                                'DemoDataWellKnownValues', 'MaterialHandlingEquipmentInterface'},
        'AtlPersonnel': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'AtlFoundation',
                         'Calendar', 'ContactPerson', 'Currency', 'Dimensions', 'Directory', 'PersonnelCore',
                         'PersonnelManagement', 'SourceDocumentation', 'SourceDocumentationTypes'},
        'AtlSampleTests': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'AtlCoreFinancial',
                           'AtlCostAccounting', 'AtlFoundation', 'AtlPersonnel', 'Currency', 'DemoDataWellKnownValues',
                           'Dimensions', 'GeneralLedger', 'Ledger', 'PersonnelCore', 'SourceDocumentation',
                           'SourceDocumentationTypes', 'UnitOfMeasure'},
        'BankTypes': {'ApplicationPlatform'},
        'BusinessProcess': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'Directory',
                            'PersonnelCore'},
        'CDSVirtualEntity': {'ApplicationFoundation', 'ApplicationPlatform'},
        'Calendar': {'Directory', 'ApplicationFoundation', 'ApplicationPlatform'},
        'CaseManagement': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'ContactPerson',
                           'Directory', 'PersonnelCore'},
        'CommunityDrivenEngineeringTests': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform',
                                            'AtlFoundation', 'AtlPersonnel', 'ContactPerson', 'DemoDataWellKnownValues',
                                            'Directory', 'FiscalBooks', 'Ledger', 'PersonnelCore', 'Retail',
                                            'SourceDocumentation', 'SourceDocumentationTypes', 'Tax', 'UnitOfMeasure'},
        'ContactPerson': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'DataSharing',
                          'Directory'},
        'CostAccounting': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'Calendar', 'Currency',
                           'UnitOfMeasure'},
        'CostAccountingAX': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'Calendar',
                             'CostAccounting', 'Currency', 'Dimensions', 'Directory', 'GeneralLedger', 'Ledger',
                             'PersonnelCore', 'PersonnelManagement', 'Retail', 'SourceDocumentationTypes', 'Subledger'},
        'CostAccountingService': {'ApplicationFoundation', 'ApplicationPlatform', 'Calendar', 'CostAccounting',
                                  'CostAccountingAX', 'Currency', 'Directory', 'FiscalBooks', 'Ledger', 'Retail',
                                  'SourceDocumentation', 'SourceDocumentationTypes', 'Tax', 'UnitOfMeasure'},
        'CreditManagement': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'BankTypes',
                             'Calendar', 'CaseManagement', 'ContactPerson', 'Currency', 'Dimensions', 'Directory',
                             'FiscalBooks', 'GeneralLedger', 'Ledger', 'PersonnelCore', 'PersonnelManagement',
                             'Project', 'Retail', 'SourceDocumentation', 'SourceDocumentationTypes', 'Subledger', 'Tax',
                             'TaxEngine', 'UnitOfMeasure'},
        'Currency': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'Directory'},
        'CustomFields': {'ApplicationFoundation', 'ApplicationPlatform', 'MetadataExport'},
        'DOM': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'Calendar', 'ContactPerson',
                'Dimensions', 'Directory', 'FiscalBooks', 'GeneralLedger', 'InventoryDimensionConversion', 'Ledger',
                'Retail', 'SourceDocumentation', 'SourceDocumentationTypes', 'Tax', 'UnitOfMeasure'},
        'DataExpansionTool': {'ApplicationFoundation', 'ApplicationPlatform'},
        'DataFeeds': {'ApplicationFoundation', 'ApplicationPlatform', 'MetadataExport'},
        'DataImpExpApplication': {'ApplicationFoundation', 'ApplicationPlatform', 'Currency', 'Dimensions', 'Directory',
                                  'Ledger', 'Retail', 'SourceDocumentation', 'SourceDocumentationTypes', 'Tax',
                                  'UnitOfMeasure'},
        'DataMaintenance': {'ApplicationFoundation', 'ApplicationPlatform', 'DataMaintenanceTypes',
                            'ProcessAutomation'},
        'DataMaintenanceTypes': {'ApplicationPlatform'},
        'DataSharing': {'ApplicationFoundation', 'ApplicationPlatform'},
        'DataUpgrade': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'BankTypes', 'Calendar',
                        'CaseManagement', 'ContactPerson', 'CostAccounting', 'Currency', 'DOM', 'Dimensions',
                        'Directory', 'DirectoryUpgrade', 'ElectronicReporting', 'ElectronicReportingCore',
                        'ElectronicReportingMapping', 'FinanceInsightsContracts', 'FiscalBooks', 'GeneralLedger',
                        'InventoryDimensionConversion', 'Ledger', 'Measurement', 'PersonnelCore', 'PersonnelManagement',
                        'Policy', 'Project', 'ProjectMobile', 'Retail', 'SourceDocumentation',
                        'SourceDocumentationTypes', 'Subledger', 'Tax', 'TaxEngine', 'UnitOfMeasure',
                        'WMSAdvancedMigration'},
        'DemoDataSuite': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationFoundationFormAdaptor',
                          'ApplicationPlatform', 'ApplicationPlatformFormAdaptor', 'ApplicationWorkspaces',
                          'CaseManagement', 'ContactPerson', 'Dimensions', 'Directory', 'FiscalBooks', 'Ledger',
                          'PersonnelCore', 'PersonnelManagement', 'Retail', 'SelfHealing', 'SelfHealingRules',
                          'SourceDocumentation', 'SourceDocumentationTypes', 'Tax', 'TestEssentials', 'UnitOfMeasure'},
        'DemoDataWellKnownValues': {'ApplicationFoundation', 'ApplicationPlatform', 'Currency', 'Ledger',
                                    'TestEssentials'},
        'Dimensions': {'ApplicationFoundation', 'ApplicationPlatform', 'DataMaintenanceTypes', 'Directory',
                       'MetadataExport'},
        'Directory': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform'},
        'DirectoryUpgrade': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'Directory'},
        'ElectronicReporting': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'Directory',
                                'ElectronicReportingCore', 'ElectronicReportingDotNetUtils', 'ElectronicReportingForAx',
                                'ElectronicReportingInternal', 'ElectronicReportingMapping'},
        'ElectronicReportingAppSuiteIntegration': {'ApplicationFoundation', 'ApplicationPlatform', 'BankTypes',
                                                   'Currency', 'Directory', 'ElectronicReporting',
                                                   'ElectronicReportingCore', 'ElectronicReportingDotNetUtils',
                                                   'ElectronicReportingForAx', 'ElectronicReportingMapping', 'Ledger'},
        'ElectronicReportingBusinessDoc': {'ApplicationFoundation', 'ApplicationPlatform', 'Directory',
                                           'ElectronicReporting', 'ElectronicReportingCore',
                                           'ElectronicReportingDotNetUtils', 'ElectronicReportingForAx',
                                           'ElectronicReportingMapping'},
        'ElectronicReportingCore': {'ApplicationFoundation', 'ApplicationPlatform', 'Directory',
                                    'ElectronicReportingDotNetUtils'},
        'ElectronicReportingDotNetUtils': {'ApplicationFoundation', 'ApplicationPlatform', 'Directory'},
        'ElectronicReportingForAx': {'ApplicationFoundation', 'ApplicationPlatform', 'ElectronicReportingCore',
                                     'ElectronicReportingDotNetUtils', 'ElectronicReportingMapping'},
        'ElectronicReportingForRetail': {'ApplicationFoundation', 'ApplicationPlatform', 'ElectronicReporting',
                                         'ElectronicReportingCore', 'ElectronicReportingDotNetUtils',
                                         'ElectronicReportingMapping'},
        'ElectronicReportingInternal': {'ApplicationFoundation', 'ApplicationPlatform', 'Directory',
                                        'ElectronicReportingCore', 'ElectronicReportingDotNetUtils',
                                        'ElectronicReportingForAx', 'ElectronicReportingMapping'},
        'ElectronicReportingMapping': {'ApplicationFoundation', 'ApplicationPlatform', 'ElectronicReportingCore',
                                       'ElectronicReportingDotNetUtils'},
        'EngineeringChangeManagement': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform',
                                        'BankTypes', 'BusinessProcess', 'Calendar', 'CaseManagement', 'ContactPerson',
                                        'Currency', 'DataSharing', 'Dimensions', 'Directory', 'ElectronicReporting',
                                        'ElectronicReportingCore', 'ElectronicReportingForAx',
                                        'ElectronicReportingMapping', 'FinancialReporting', 'FiscalBooks',
                                        'GeneralLedger', 'Ledger', 'Measurement', 'Personnel', 'PersonnelCore',
                                        'PersonnelManagement', 'Policy', 'Project', 'Retail', 'SourceDocumentation',
                                        'SourceDocumentationTypes', 'Subledger', 'Tax', 'TaxEngine', 'UnitOfMeasure'},
        'EntAssetManufacturingExecution': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform',
                                           'CaseManagement', 'Directory', 'EnterpriseAssetManagementAppSuite',
                                           'MessageProcessor', 'PersonnelCore', 'PersonnelManagement', 'UnitOfMeasure',
                                           'WorkloadCommon'},
        'EntAssetManufacturingExecutionBackoffice': {'ApplicationCommon', 'ApplicationFoundation',
                                                     'ApplicationPlatform', 'CaseManagement', 'Directory',
                                                     'EntAssetManufacturingExecution',
                                                     'EnterpriseAssetManagementAppSuite',
                                                     'ManufacturingExecutionBackoffice', 'MessageProcessor',
                                                     'PersonnelCore', 'PersonnelManagement', 'ScaleUnitManagement',
                                                     'SourceDocumentationTypes', 'UnitOfMeasure', 'WorkloadCommon'},
        'EntAssetManufacturingExecutionInterface': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform',
                                                    'Directory', 'EntAssetManufacturingExecution',
                                                    'EnterpriseAssetManagementAppSuite',
                                                    'ManufacturingExecutionInterface', 'PersonnelCore',
                                                    'PersonnelManagement', 'UnitOfMeasure'},
        'EnterpriseAssetManagementAppSuite': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform',
                                              'BankTypes', 'BusinessProcess', 'Calendar', 'CaseManagement',
                                              'ContactPerson', 'Currency', 'DataSharing', 'Dimensions', 'Directory',
                                              'ElectronicReporting', 'ElectronicReportingCore',
                                              'ElectronicReportingForAx', 'ElectronicReportingMapping',
                                              'FinancialReporting', 'FiscalBooks', 'GeneralLedger', 'Ledger',
                                              'Measurement', 'MixedRealityCore', 'Personnel', 'PersonnelCore',
                                              'PersonnelManagement', 'Policy', 'Project', 'Retail',
                                              'SourceDocumentation', 'SourceDocumentationTypes', 'Subledger', 'Tax',
                                              'TaxEngine', 'UnitOfMeasure'},
        'EnterpriseAssetManagementIot': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform',
                                         'Directory', 'EnterpriseAssetManagementAppSuite', 'IoTIntelligenceCore',
                                         'IoTIntelligenceManufacturing', 'PersonnelCore'},
        'EnterpriseAssetManagementMobile': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform',
                                            'BankTypes', 'BusinessProcess', 'Calendar', 'CaseManagement',
                                            'ContactPerson', 'Currency', 'DataSharing', 'Dimensions', 'Directory',
                                            'ElectronicReporting', 'ElectronicReportingCore',
                                            'ElectronicReportingForAx', 'ElectronicReportingMapping',
                                            'EnterpriseAssetManagementAppSuite', 'FinancialReporting', 'FiscalBooks',
                                            'GeneralLedger', 'Ledger', 'Measurement', 'MixedRealityCore', 'Personnel',
                                            'PersonnelCore', 'PersonnelManagement', 'Policy', 'Project', 'Retail',
                                            'SourceDocumentation', 'SourceDocumentationTypes', 'Subledger', 'Tax',
                                            'TaxEngine', 'UnitOfMeasure'},
        'ExpenseManagement': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'BankTypes',
                              'CaseManagement', 'ContactPerson', 'Currency', 'Dimensions', 'Directory', 'ExpenseMobile',
                              'FiscalBooks', 'Ledger', 'Measurement', 'PersonnelCore', 'Policy', 'Project', 'Retail',
                              'SourceDocumentation', 'SourceDocumentationTypes', 'Subledger', 'Tax'},
        'ExpenseMobile': {'ApplicationFoundation', 'ApplicationPlatform', 'BankTypes', 'CaseManagement',
                          'ContactPerson', 'Currency', 'Dimensions', 'Directory', 'FiscalBooks', 'Ledger',
                          'Measurement', 'PersonnelCore', 'Project', 'Retail', 'SourceDocumentation',
                          'SourceDocumentationTypes', 'Tax'},
        'FinanceInsightsContracts': {'ApplicationFoundation', 'ApplicationPlatform', 'Currency', 'Ledger',
                                     'ProcessAutomation', 'SourceDocumentationTypes'},
        'FinancialDimensionService': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'Dimensions',
                                      'Ledger'},
        'FinancialReporting': {'ApplicationFoundation', 'ApplicationPlatform', 'Calendar', 'Currency', 'Dimensions',
                               'Directory', 'GeneralLedger', 'Ledger', 'SourceDocumentationTypes', 'UnitOfMeasure'},
        'FinancialReportingEntityStore': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform',
                                          'Calendar', 'ContactPerson', 'Currency', 'Dimensions', 'Directory',
                                          'FinancialReporting', 'FiscalBooks', 'GeneralLedger', 'Ledger',
                                          'PersonnelCore', 'SourceDocumentation', 'SourceDocumentationTypes',
                                          'Subledger', 'Tax', 'UnitOfMeasure'},
        'FiscalBooks': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'BankTypes', 'Calendar',
                        'Currency', 'Dimensions', 'Directory', 'ElectronicReporting', 'ElectronicReportingCore',
                        'ElectronicReportingForAx', 'ElectronicReportingMapping', 'Ledger', 'SourceDocumentation',
                        'SourceDocumentationTypes', 'Tax', 'UnitOfMeasure'},
        'FiscalBooksFormAdaptor': {'ApplicationFoundation', 'ApplicationPlatform', 'FiscalBooks', 'TestEssentials'},
        'FleetManagement': {'ApplicationFoundation', 'ApplicationPlatform', 'Dimensions', 'Directory',
                            'SourceDocumentation'},
        'FleetManagementExtension': {'ApplicationFoundation', 'ApplicationPlatform', 'Dimensions', 'Directory',
                                     'FleetManagement'},
        'FleetManagementUnitTests': {'ApplicationFoundation', 'ApplicationPlatform', 'Directory', 'FleetManagement',
                                     'FleetManagementExtension', 'TestEssentials'},
        'GeneralLedger': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'Calendar', 'Currency',
                          'DataMaintenanceTypes', 'Dimensions', 'Directory', 'Ledger', 'SourceDocumentation',
                          'SourceDocumentationTypes', 'Subledger'},
        'GeneralLedgerFormAdaptor': {'ApplicationFoundation', 'ApplicationPlatform', 'Directory', 'GeneralLedger',
                                     'TestEssentials'},
        'GlobalUnifiedPricing': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'BankTypes',
                                 'ContactPerson', 'Currency', 'Dimensions', 'Directory', 'FiscalBooks', 'GeneralLedger',
                                 'Ledger', 'PersonnelCore', 'PersonnelManagement', 'RebatesAndDeductions', 'Retail',
                                 'RevenueRecognition', 'SourceDocumentation', 'SourceDocumentationTypes', 'Tax',
                                 'TaxEngine', 'UnitOfMeasure'},
        'InboundTransportationManagement': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform',
                                            'BusinessProcess', 'Calendar', 'CaseManagement', 'ContactPerson',
                                            'Currency', 'Dimensions', 'Directory', 'FiscalBooks', 'GeneralLedger',
                                            'Ledger', 'Measurement', 'PersonnelCore', 'PersonnelManagement',
                                            'ProcessGuide', 'Retail', 'SourceDocumentation', 'SourceDocumentationTypes',
                                            'Subledger', 'Tax', 'TaxEngine', 'UnitOfMeasure'},
        'InventoryDimensionConversion': {'ApplicationFoundation', 'ApplicationPlatform', 'Directory', 'FiscalBooks',
                                         'Ledger', 'SourceDocumentation', 'SourceDocumentationTypes', 'Tax'},
        'IoTIntelligenceCore': {'ApplicationFoundation', 'ApplicationPlatform'},
        'IoTIntelligenceManufacturing': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform',
                                         'Directory', 'IoTIntelligenceCore', 'UnitOfMeasure'},
        'Kitting': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'Calendar', 'CaseManagement',
                    'ContactPerson', 'Currency', 'Dimensions', 'Directory', 'FiscalBooks', 'Ledger', 'PersonnelCore',
                    'PersonnelManagement', 'Retail', 'SourceDocumentation', 'SourceDocumentationTypes', 'Subledger',
                    'Tax', 'TaxEngine', 'UnitOfMeasure'},
        'Ledger': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'Calendar', 'Currency',
                   'DataMaintenanceTypes', 'Dimensions', 'Directory', 'SourceDocumentationTypes', 'UnitOfMeasure'},
        'ManufacturingExecution': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform',
                                   'CaseManagement', 'Directory', 'ManufacturingExecutionInterface', 'MessageProcessor',
                                   'PersonnelCore', 'PersonnelManagement', 'UnitOfMeasure', 'WorkloadCommon'},
        'ManufacturingExecutionBackoffice': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform',
                                             'CaseManagement', 'Directory', 'ManufacturingExecution',
                                             'ManufacturingExecutionInterface', 'MessageProcessor', 'MixedRealityCore',
                                             'PersonnelCore', 'PersonnelManagement', 'ScaleUnitManagement',
                                             'SourceDocumentationTypes', 'UnitOfMeasure', 'WorkloadCommon'},
        'ManufacturingExecutionCommon': {'ApplicationFoundation', 'ApplicationPlatform', 'Dimensions', 'Directory',
                                         'MessageProcessor', 'PersonnelCore', 'SourceDocumentationTypes',
                                         'UnitOfMeasure'},
        'ManufacturingExecutionInterface': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform',
                                            'CaseManagement', 'Dimensions', 'Directory', 'Ledger', 'PersonnelCore',
                                            'PersonnelManagement', 'SourceDocumentationTypes', 'UnitOfMeasure'},
        'ManufacturingExecutionThirdParty': {'ApplicationFoundation', 'ApplicationPlatform', 'Dimensions',
                                             'ManufacturingExecutionCommon', 'MessageProcessor'},
        'MasterPlanningService': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'Directory',
                                  'FiscalBooks', 'Ledger', 'Retail', 'SourceDocumentation', 'SourceDocumentationTypes',
                                  'Tax'},
        'MaterialHandlingEquipmentInterface': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform',
                                               'Currency', 'Dimensions', 'Directory', 'FinancialReporting',
                                               'FiscalBooks', 'GeneralLedger', 'Ledger', 'PersonnelCore', 'Project',
                                               'Retail', 'Tax', 'UnitOfMeasure'},
        'Measurement': {'ApplicationFoundation', 'ApplicationPlatform'},
        'MessageProcessor': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform'},
        'MetadataExport': {'ApplicationFoundation', 'ApplicationPlatform'},
        'MixedRealityCore': {'ApplicationFoundation', 'ApplicationPlatform'},
        'MixedRealityManufacturing': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'Directory',
                                      'Ledger', 'ManufacturingExecutionInterface', 'MixedRealityCore', 'PersonnelCore'},
        'OperationalInsights': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform'},
        'PaymentPredictor': {'ApplicationFoundation', 'ApplicationPlatform', 'ApplicationWorkspaces', 'CaseManagement',
                             'ContactPerson', 'Currency', 'DataMaintenanceTypes', 'Directory',
                             'FinanceInsightsContracts', 'FiscalBooks', 'GeneralLedger', 'Ledger', 'Retail',
                             'SourceDocumentationTypes', 'Tax'},
        'Personnel': {'ApplicationFoundation', 'ApplicationPlatform', 'Dimensions', 'Directory', 'PersonnelCore',
                      'PersonnelManagement'},
        'PersonnelCore': {'ApplicationFoundation', 'ApplicationPlatform', 'Calendar', 'Currency', 'Dimensions',
                          'Directory', 'Measurement', 'SourceDocumentation', 'SourceDocumentationTypes',
                          'UnitOfMeasure'},
        'PersonnelManagement': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'BankTypes',
                                'BusinessProcess', 'Calendar', 'CaseManagement', 'ContactPerson', 'Currency',
                                'Dimensions', 'Directory', 'ElectronicReporting', 'ElectronicReportingCore',
                                'ElectronicReportingMapping', 'Measurement', 'PersonnelCore', 'Policy',
                                'SourceDocumentation', 'SourceDocumentationTypes', 'UnitOfMeasure'},
        'PersonnelMobile': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'BankTypes',
                            'BusinessProcess', 'Calendar', 'CaseManagement', 'ContactPerson', 'Currency', 'Dimensions',
                            'Directory', 'Measurement', 'Personnel', 'PersonnelCore', 'PersonnelManagement', 'Policy',
                            'SourceDocumentation', 'SourceDocumentationTypes', 'UnitOfMeasure'},
        'PersonnelUpgrade': {'ApplicationFoundation', 'ApplicationPlatform', 'BusinessProcess', 'Directory',
                             'DirectoryUpgrade', 'Personnel', 'PersonnelCore', 'PersonnelManagement'},
        'Policy': {'Directory', 'ApplicationFoundation', 'ApplicationPlatform'},
        'ProcessAutomation': {'ApplicationFoundation', 'ApplicationPlatform', 'Directory'},
        'ProcessGuide': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'Dimensions', 'Directory',
                         'Ledger', 'PersonnelCore', 'UnitOfMeasure'},
        'Project': {'ApplicationFoundation', 'ApplicationPlatform', 'Directory', 'Measurement'},
        'ProjectMobile': {'ApplicationFoundation', 'ApplicationPlatform', 'Calendar', 'CaseManagement', 'ContactPerson',
                          'Currency', 'Dimensions', 'Directory', 'GeneralLedger', 'Measurement', 'Personnel',
                          'PersonnelCore', 'Project', 'Retail', 'SourceDocumentation', 'SourceDocumentationTypes',
                          'Tax'},
        'ProjectOperations': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'Calendar',
                              'CaseManagement', 'Currency', 'Dimensions', 'Directory', 'FiscalBooks', 'Ledger',
                              'Measurement', 'PersonnelCore', 'Project', 'SourceDocumentation',
                              'SourceDocumentationTypes', 'Subledger', 'Tax', 'UnitOfMeasure'},
        'PublicSector': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'BankTypes', 'Calendar',
                         'CaseManagement', 'ContactPerson', 'CostAccounting', 'Currency', 'Dimensions', 'Directory',
                         'ElectronicReporting', 'FinanceInsightsContracts', 'FiscalBooks', 'GeneralLedger', 'Ledger',
                         'Measurement', 'Personnel', 'PersonnelCore', 'PersonnelManagement', 'Policy', 'Project',
                         'Retail', 'SourceDocumentation', 'SourceDocumentationTypes', 'Subledger', 'Tax',
                         'UnitOfMeasure'},
        'PublicSectorFormAdaptor': {'ApplicationFoundation', 'ApplicationPlatform', 'PublicSector', 'TestEssentials'},
        'RebatesAndDeductions': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'BankTypes',
                                 'BusinessProcess', 'Calendar', 'CaseManagement', 'ContactPerson', 'CostAccounting',
                                 'Currency', 'Dimensions', 'Directory', 'ElectronicReporting',
                                 'ElectronicReportingCore', 'ElectronicReportingForAx', 'ElectronicReportingMapping',
                                 'FinanceInsightsContracts', 'FiscalBooks', 'GeneralLedger', 'Ledger', 'Measurement',
                                 'Personnel', 'PersonnelCore', 'PersonnelManagement', 'Policy', 'Project', 'Retail',
                                 'SourceDocumentation', 'SourceDocumentationTypes', 'Subledger', 'Tax', 'TaxEngine',
                                 'UnitOfMeasure'},
        'RegulatoryServices': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'ContactPerson',
                               'Directory', 'ElectronicReporting', 'ElectronicReportingCore',
                               'ElectronicReportingDotNetUtils', 'ElectronicReportingMapping',
                               'FinanceInsightsContracts', 'FiscalBooks', 'Ledger', 'Retail', 'SourceDocumentation',
                               'SourceDocumentationTypes', 'Tax'},
        'Retail': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'CaseManagement', 'Currency',
                   'Dimensions', 'Directory', 'GeneralLedger', 'Ledger', 'PersonnelCore', 'PersonnelManagement',
                   'SourceDocumentationTypes', 'UnitOfMeasure'},
        'RetailEod': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'Calendar', 'ContactPerson',
                      'Currency', 'Dimensions', 'Directory', 'ElectronicReportingCore', 'FiscalBooks', 'GeneralLedger',
                      'InventoryDimensionConversion', 'Ledger', 'Personnel', 'PersonnelCore', 'PersonnelManagement',
                      'Retail', 'SourceDocumentation', 'SourceDocumentationTypes', 'Tax', 'TaxEngine', 'UnitOfMeasure'},
        'RetailFormAdaptor': {'ApplicationFoundation', 'ApplicationPlatform', 'Currency', 'Dimensions', 'Directory',
                              'GeneralLedger', 'Ledger', 'PersonnelCore', 'PersonnelManagement', 'Retail',
                              'SourceDocumentationTypes', 'TestEssentials', 'UnitOfMeasure'},
        'RetailTeamsIntegration': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform',
                                   'BusinessProcess', 'Directory', 'FiscalBooks', 'PersonnelCore', 'Retail'},
        'RevenueRecognition': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'BankTypes',
                               'Calendar', 'ContactPerson', 'Currency', 'Dimensions', 'Directory',
                               'ElectronicReporting', 'FiscalBooks', 'GeneralLedger', 'Ledger', 'PersonnelCore',
                               'Project', 'Retail', 'SourceDocumentation', 'SourceDocumentationTypes', 'Subledger',
                               'Tax', 'TaxEngine', 'UnitOfMeasure'},
        'SCMInsights': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'CaseManagement',
                        'ContactPerson', 'Currency', 'Dimensions', 'Directory', 'FinanceInsightsContracts',
                        'FiscalBooks', 'GeneralLedger', 'Ledger', 'ProcessAutomation', 'SourceDocumentation',
                        'SourceDocumentationTypes', 'Subledger', 'Tax', 'UnitOfMeasure'},
        'SCMMobile': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'Calendar', 'CaseManagement',
                      'ContactPerson', 'CostAccounting', 'Currency', 'Dimensions', 'Directory', 'FiscalBooks', 'Ledger',
                      'PersonnelManagement', 'Retail', 'SourceDocumentation', 'SourceDocumentationTypes', 'Tax'},
        'ScaleUnitDatapipeline': {'ApplicationFoundation', 'ApplicationPlatform', 'Retail', 'ScaleUnitManagement',
                                  'WorkloadCommon'},
        'ScaleUnitManagement': {'ApplicationFoundation', 'ApplicationPlatform', 'Directory', 'FiscalBooks',
                                'MessageProcessor', 'Retail', 'WorkloadCommon'},
        'SelfHealing': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'PersonnelManagement'},
        'SelfHealingRules': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'Directory',
                             'FiscalBooks', 'GeneralLedger', 'IoTIntelligenceCore', 'IoTIntelligenceManufacturing',
                             'Ledger', 'ProcessAutomation', 'Project', 'Retail', 'SelfHealing', 'SourceDocumentation',
                             'SourceDocumentationTypes', 'Subledger', 'Tax', 'TaxEngine', 'UnitOfMeasure'},
        'SourceDocumentation': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'Calendar',
                                'Currency', 'Dimensions', 'Directory', 'SourceDocumentationTypes', 'UnitOfMeasure'},
        'SourceDocumentationTypes': {'ApplicationFoundation', 'ApplicationPlatform', 'Calendar', 'Currency',
                                     'Dimensions', 'Directory', 'UnitOfMeasure'},
        'Subledger': {'ApplicationFoundation', 'ApplicationPlatform', 'Calendar', 'Currency', 'Dimensions', 'Directory',
                      'Ledger', 'ProcessAutomation', 'SourceDocumentation', 'SourceDocumentationTypes'},
        'SystemHealth': {'ApplicationFoundation', 'ApplicationPlatform'},
        'Tax': {'ApplicationFoundation', 'ApplicationPlatform', 'Dimensions', 'Directory', 'Ledger',
                'SourceDocumentationTypes'},
        'TaxEngine': {'ApplicationFoundation', 'ApplicationPlatform', 'Currency', 'Dimensions', 'Directory',
                      'ElectronicReporting', 'ElectronicReportingCore', 'ElectronicReportingDotNetUtils',
                      'ElectronicReportingForAx', 'ElectronicReportingInternal', 'ElectronicReportingMapping', 'Ledger',
                      'SourceDocumentationTypes'},
        'TestEssentials': {'ApplicationFoundation', 'ApplicationPlatform'},
        'TimesheetMobile': {'ApplicationFoundation', 'ApplicationPlatform', 'Calendar', 'CaseManagement',
                            'ContactPerson', 'Currency', 'Dimensions', 'Directory', 'GeneralLedger', 'Measurement',
                            'Personnel', 'PersonnelCore', 'PersonnelManagement', 'Project', 'SourceDocumentation',
                            'SourceDocumentationTypes', 'Tax'},
        'Tutorial': {'ApplicationFoundation', 'ApplicationPlatform'},
        'UnitOfMeasure': {'Directory', 'ApplicationFoundation', 'ApplicationPlatform'},
        'WHSAppTaskValidator': {'ApplicationFoundation', 'ApplicationPlatform', 'UnitOfMeasure'},
        'WMSAdvancedMigration': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'Dimensions',
                                 'Directory', 'InventoryDimensionConversion', 'Ledger'},
        'WarehouseExecutionWorkload': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform',
                                       'Dimensions', 'Directory', 'FiscalBooks', 'Ledger',
                                       'ManufacturingExecutionCommon', 'MessageProcessor', 'PersonnelCore',
                                       'ScaleUnitManagement', 'SourceDocumentation', 'SourceDocumentationTypes', 'Tax',
                                       'UnitOfMeasure', 'WarehouseExecutionWorkloadBackoffice', 'WarehousePlanning',
                                       'WorkloadCommon'},
        'WarehouseExecutionWorkloadBackoffice': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform',
                                                 'ContactPerson', 'Dimensions', 'Directory', 'FiscalBooks', 'Ledger',
                                                 'MessageProcessor', 'PersonnelCore', 'Retail', 'ScaleUnitManagement',
                                                 'SourceDocumentation', 'SourceDocumentationTypes', 'Tax',
                                                 'UnitOfMeasure', 'WarehousePlanning', 'WorkloadCommon'},
        'WarehousePlanning': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'Directory',
                              'UnitOfMeasure', 'WorkloadCommon'},
        'WorkloadCommon': {'ApplicationCommon', 'ApplicationFoundation', 'ApplicationPlatform', 'CustomFields',
                           'Directory', 'Ledger', 'MessageProcessor', 'PersonnelCore', 'PersonnelManagement',
                           'TaxEngine'}
    }


def test_get_package_references_without_filter(log):
    config.set('DEFAULTS', 'package_filter', '')
    result = PackageReference().run()

    assert result == {}


def test_get_build_order_with_packages_filter(log):
    result = BuildOrder(['Application.*']).run()

    assert list(result) == [
        {'ApplicationPlatform'},
        {'ApplicationFoundation', 'ApplicationPlatformFormAdaptor'},
        {'ApplicationCommon', 'ApplicationFoundationFormAdaptor', 'ApplicationSuiteFormAdaptor'},
        {'ApplicationWorkspaces'},
        {'ApplicationWorkspacesFormAdaptor'}
    ]


def test_get_build_order_catch_all_filter(log):
    config.set('DEFAULTS', 'package_filter', '.*')
    result = BuildOrder().run()

    assert list(result) == [
        {'ApplicationPlatform'},
        {'BankTypes', 'ApplicationFoundation', 'DataMaintenanceTypes'},
        {'ApplicationCommon', 'AtlFoundation', 'CDSVirtualEntity', 'DataExpansionTool', 'DataSharing',
         'IoTIntelligenceCore', 'Measurement', 'MetadataExport', 'MixedRealityCore', 'SystemHealth', 'TestEssentials',
         'Tutorial'},
        {'AppTroubleshootingCore', 'ApplicationFoundationFormAdaptor', 'ApplicationPlatformFormAdaptor', 'CustomFields',
         'DataFeeds', 'Directory', 'MessageProcessor', 'OperationalInsights'},
        {'Calendar', 'ContactPerson', 'Currency', 'Dimensions', 'DirectoryUpgrade', 'ElectronicReportingDotNetUtils',
         'Policy', 'ProcessAutomation', 'Project', 'UnitOfMeasure'},
        {'CostAccounting', 'DataMaintenance', 'ElectronicReportingCore', 'IoTIntelligenceManufacturing',
         'SourceDocumentationTypes', 'WHSAppTaskValidator'},
        {'SourceDocumentation', 'ElectronicReportingMapping', 'Ledger'},
        {'AtlCoreFinancial', 'AtlCostAccounting', 'DemoDataWellKnownValues', 'ElectronicReportingForAx',
         'FinanceInsightsContracts', 'FinancialDimensionService', 'FleetManagement', 'PersonnelCore', 'Subledger',
         'Tax'},
        {'BusinessProcess', 'CaseManagement', 'ElectronicReportingInternal', 'FleetManagementExtension',
         'GeneralLedger', 'ManufacturingExecutionCommon', 'ProcessGuide'},
        {'ElectronicReporting', 'FinancialReporting', 'FleetManagementUnitTests', 'GeneralLedgerFormAdaptor',
         'ManufacturingExecutionThirdParty'},
        {'ElectronicReportingAppSuiteIntegration', 'ElectronicReportingBusinessDoc', 'ElectronicReportingForRetail',
         'FiscalBooks', 'PersonnelManagement', 'TaxEngine'},
        {'AccountsPayableMobile', 'AtlPersonnel', 'FinancialReportingEntityStore', 'FiscalBooksFormAdaptor',
         'InventoryDimensionConversion', 'ManufacturingExecutionInterface', 'Personnel', 'ProjectOperations', 'Retail',
         'SCMInsights', 'SelfHealing', 'WorkloadCommon'},
        {'ApplicationSuiteFormAdaptor', 'AssetLeasing', 'AtlSampleTests', 'CommunityDrivenEngineeringTests',
         'CostAccountingAX', 'CreditManagement', 'DOM', 'DataImpExpApplication', 'EngineeringChangeManagement',
         'EnterpriseAssetManagementAppSuite', 'ExpenseMobile', 'InboundTransportationManagement', 'Kitting',
         'ManufacturingExecution', 'MasterPlanningService', 'MaterialHandlingEquipmentInterface',
         'MixedRealityManufacturing', 'PersonnelMobile', 'PersonnelUpgrade', 'ProjectMobile', 'PublicSector',
         'RebatesAndDeductions', 'RegulatoryServices', 'RetailEod', 'RetailFormAdaptor', 'RetailTeamsIntegration',
         'RevenueRecognition', 'SCMMobile', 'ScaleUnitManagement', 'SelfHealingRules', 'TimesheetMobile',
         'WMSAdvancedMigration', 'WarehousePlanning'},
        {'AppTroubleshooting', 'ApplicationWorkspaces', 'AtlMaterialhandling', 'CostAccountingService', 'DataUpgrade',
         'EntAssetManufacturingExecution', 'EnterpriseAssetManagementIot', 'EnterpriseAssetManagementMobile',
         'ExpenseManagement', 'GlobalUnifiedPricing', 'ManufacturingExecutionBackoffice', 'PublicSectorFormAdaptor',
         'ScaleUnitDatapipeline', 'WarehouseExecutionWorkloadBackoffice'},
        {'ATLApplicationSuite', 'ApplicationWorkspacesFormAdaptor', 'DemoDataSuite',
         'EntAssetManufacturingExecutionBackoffice', 'EntAssetManufacturingExecutionInterface', 'PaymentPredictor',
         'WarehouseExecutionWorkload'}
    ]


def test_get_build_order_without_filter(log):
    config.set('DEFAULTS', 'package_filter', '')
    result = BuildOrder().run()

    assert list(result) == []


def test_build_one_module(log):
    Builder(['ApplicationWorkspacesFormAdaptor']).run()

    assert log == [
        f'LOG:INFO:Build: {PACKAGES_DIR}',
        'LOG:None:  Level: 0',
        'LOG:None:  Building: ApplicationWorkspacesFormAdaptor',
        f'FOLDER:CREATE:{LOG_DIR}/ApplicationWorkspacesFormAdaptor',
        f'CALL:#{PACKAGES_DIR}#ApplicationWorkspacesFormAdaptor#{LOG_DIR}#:shell=True'
    ]


def test_build(log):
    Builder(['Application.*']).run()

    assert log == [
        f'LOG:INFO:Build: {PACKAGES_DIR}',
        'LOG:None:  Level: 0',
        'LOG:None:  Building: ApplicationPlatform',
        f'FOLDER:CREATE:{LOG_DIR}/ApplicationPlatform',
        f'CALL:#{PACKAGES_DIR}#ApplicationPlatform#{LOG_DIR}#:shell=True',
        'LOG:None:  Level: 1',
        'LOG:None:  Building: ApplicationFoundation',
        f'FOLDER:CREATE:{LOG_DIR}/ApplicationFoundation',
        f'CALL:#{PACKAGES_DIR}#ApplicationFoundation#{LOG_DIR}#:shell=True',
        'LOG:None:  Building: ApplicationPlatformFormAdaptor',
        f'FOLDER:CREATE:{LOG_DIR}/ApplicationPlatformFormAdaptor',
        f'CALL:#{PACKAGES_DIR}#ApplicationPlatformFormAdaptor#{LOG_DIR}#:shell=True',
        'LOG:None:  Level: 2',
        'LOG:None:  Building: ApplicationCommon',
        f'FOLDER:CREATE:{LOG_DIR}/ApplicationCommon',
        f'CALL:#{PACKAGES_DIR}#ApplicationCommon#{LOG_DIR}#:shell=True',
        'LOG:None:  Building: ApplicationFoundationFormAdaptor',
        f'FOLDER:CREATE:{LOG_DIR}/ApplicationFoundationFormAdaptor',
        f'CALL:#{PACKAGES_DIR}#ApplicationFoundationFormAdaptor#{LOG_DIR}#:shell=True',
        'LOG:None:  Building: ApplicationSuiteFormAdaptor',
        f'FOLDER:CREATE:{LOG_DIR}/ApplicationSuiteFormAdaptor',
        f'CALL:#{PACKAGES_DIR}#ApplicationSuiteFormAdaptor#{LOG_DIR}#:shell=True',
        'LOG:None:  Level: 3',
        'LOG:None:  Building: ApplicationWorkspaces',
        f'FOLDER:CREATE:{LOG_DIR}/ApplicationWorkspaces',
        f'CALL:#{PACKAGES_DIR}#ApplicationWorkspaces#{LOG_DIR}#:shell=True',
        'LOG:None:  Level: 4',
        'LOG:None:  Building: ApplicationWorkspacesFormAdaptor',
        f'FOLDER:CREATE:{LOG_DIR}/ApplicationWorkspacesFormAdaptor',
        f'CALL:#{PACKAGES_DIR}#ApplicationWorkspacesFormAdaptor#{LOG_DIR}#:shell=True'
    ]
